/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.maheevil.modbot

import com.kotlindiscord.kord.extensions.ExtensibleBot
import com.kotlindiscord.kord.extensions.utils.env
import dev.kord.common.entity.Snowflake
import io.github.maheevil.modbot.extensions.AntiScamProt
import io.github.maheevil.modbot.extensions.ModerationUtils
import io.github.maheevil.modbot.extensions.RaidProt

val TEST_SERVER_ID = Snowflake(
    env("TEST_SERVER").toLong()  // Get the test server ID from the env vars or a .env file
)

private val TOKEN = env("TOKEN")   // Get the bot' token from the env vars or a .env file

suspend fun main() {
    val bot = ExtensibleBot(TOKEN) {
        chatCommands {
            defaultPrefix = "?"
            enabled = true

            prefix { default ->
                if (guildId == TEST_SERVER_ID) "!" else default
            }
        }
        extensions {
            add(::AntiScamProt)
            add(::ModerationUtils)
            add(::RaidProt)
        }
    }

    bot.start()
}
