/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
package io.github.maheevil.modbot.extensions.util

import com.kotlindiscord.kord.extensions.extensions.Extension
import com.kotlindiscord.kord.extensions.extensions.publicSlashCommand
import com.kotlindiscord.kord.extensions.types.respond
import com.soywiz.korio.dynamic.KDynamic.Companion.toLong
import dev.kord.core.behavior.GuildBehavior
import dev.kord.core.entity.channel.TextChannel
import dev.kord.core.entity.channel.createInvite
import io.github.maheevil.modbot.guildConfigDataMap
import kotlinx.coroutines.flow.firstOrNull

class MiscCommands : Extension(){
    override val name = "misc"

    override suspend fun setup() {
        publicSlashCommand {
            name = "invite"
            description = "provides a invite link to this server"

            action{
                //Removed the guild check because this is a guild only slash command
                respond {
                    if(guild != null)
                        content = getInviteLink(channel.fetchChannel() as TextChannel, guild!!)
                    content = "This is guild only command"
                }
            }
        }
    }

    suspend fun getInviteLink(channel: TextChannel, guild: GuildBehavior) : String{
        return "https://discord.gg/" + suspend { guildConfigDataMap[guild.id.toLong()]?.invite
                    ?: channel.invites.firstOrNull()?.code
                    ?: guild.invites.firstOrNull()?.code
                    ?: channel.createInvite {
                        reason = "AutoGenerated Invite"
                        temporary = false
                    }.code
        }.invoke()
    }
}