package io.github.maheevil.modbot.extensions.util

import com.kotlindiscord.kord.extensions.extensions.Extension
import com.kotlindiscord.kord.extensions.extensions.publicSlashCommand
import com.kotlindiscord.kord.extensions.types.respond
import dev.kord.core.behavior.GuildBehavior
import dev.kord.core.entity.channel.TextChannel
import dev.kord.core.entity.channel.createInvite
import io.github.maheevil.modbot.TEST_SERVER_ID
import io.github.maheevil.modbot.inviteCode
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.firstOrNull

class MiscCommands : Extension(){
    override val name = "misc"

    override suspend fun setup() {
        publicSlashCommand {
            name = "invite"
            description = "provides a invite link to this server"
            guild(TEST_SERVER_ID)

            action{
                //Removed the guild check because this is a guild only slash command
                respond {
                    content = getInviteLink(channel.fetchChannel() as TextChannel, guild!!)
                }
            }
        }
    }

    suspend fun getInviteLink(channel: TextChannel, guild: GuildBehavior) : String{
        return "https://discord.gg/" +
                if(inviteCode == "NULL") {
                    if(channel.invites.firstOrNull() != null)
                        channel.invites.first()
                    if(guild.invites.firstOrNull() != null)
                        guild.invites.first().code
                    else channel.createInvite{
                        reason = "AutoGenerated Invite"
                        temporary = false
                    }.code
                } else inviteCode
    }
}